//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckoutKata.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineStoreEntities : DbContext
    {
        public OnlineStoreEntities()
            : base("name=OnlineStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetCartByCartId_Result> GetCartByCartId(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartByCartId_Result>("GetCartByCartId", idParameter);
        }
    
        public virtual ObjectResult<GetInventory_Result> GetInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInventory_Result>("GetInventory");
        }
    
        public virtual ObjectResult<GetOffers_Result> GetOffers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOffers_Result>("GetOffers");
        }
    
        public virtual int InsertCartItem(Nullable<System.Guid> id, string sku, Nullable<int> quantity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            var skuParameter = sku != null ?
                new ObjectParameter("sku", sku) :
                new ObjectParameter("sku", typeof(string));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCartItem", idParameter, skuParameter, quantityParameter);
        }
    }
}
